<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ecole;

class EcolesSeeder extends Seeder
{
    public function run(): void
    {
        $ecoles = [
            [
                'nom' => 'École St-Émile',
                'adresse' => '123 Rue Principale',
                'ville' => 'St-Émile',
                'province' => 'QC',
                'code_postal' => 'G0A 4A0',
                'telephone' => '418-123-4567',
                'email' => 'info@karate-stemile.ca',
                'proprietaire' => 'Jean Tremblay',
                'active' => true,
            ],
            [
                'nom' => 'Académie Sainte-Foy',
                'adresse' => '456 Boulevard Laurier',
                'ville' => 'Sainte-Foy',
                'province' => 'QC',
                'code_postal' => 'G1V 2L1',
                'telephone' => '418-234-5678',
                'email' => 'contact@academie-saintefoy.ca',
                'proprietaire' => 'Marie Dubois',
                'active' => true,
            ],
            [
                'nom' => 'Dojo de Lévis',
                'adresse' => '789 Rue de la Rive-Sud',
                'ville' => 'Lévis',
                'province' => 'QC',
                'code_postal' => 'G6V 8K2',
                'telephone' => '418-345-6789',
                'email' => 'info@dojo-levis.ca',
                'proprietaire' => 'Pierre Gagnon',
                'active' => true,
            ],
            [
                'nom' => 'Centre Sportif Val-Bélair',
                'adresse' => '321 Avenue des Sports',
                'ville' => 'Val-Bélair',
                'province' => 'QC',
                'code_postal' => 'G3K 1M5',
                'telephone' => '418-456-7890',
                'email' => 'centre@vbelair-sports.ca',
                'proprietaire' => 'Luc Bouchard',
                'active' => true,
            ],
            [
                'nom' => 'École de Karaté Charlesbourg',
                'adresse' => '654 Rue des Érables',
                'ville' => 'Charlesbourg',
                'province' => 'QC',
                'code_postal' => 'G1G 3V8',
                'telephone' => '418-567-8901',
                'email' => 'karate@charlesbourg.ca',
                'proprietaire' => 'Sylvie Morin',
                'active' => true,
            ],
            [
                'nom' => 'Dojo Beauport',
                'adresse' => '987 Avenue Royale',
                'ville' => 'Beauport',
                'province' => 'QC',
                'code_postal' => 'G1E 2B3',
                'telephone' => '418-678-9012',
                'email' => 'info@dojo-beauport.ca',
                'proprietaire' => 'Daniel Roy',
                'active' => true,
            ],
            [
                'nom' => 'Club de Karaté Ancienne-Lorette',
                'adresse' => '147 Rue Notre-Dame',
                'ville' => 'Ancienne-Lorette',
                'province' => 'QC',
                'code_postal' => 'G2E 2Z8',
                'telephone' => '418-789-0123',
                'email' => 'club@lorette-karate.ca',
                'proprietaire' => 'France Côté',
                'active' => true,
            ],
            [
                'nom' => 'Arts Martiaux Lac-Saint-Charles',
                'adresse' => '258 Chemin du Lac',
                'ville' => 'Lac-Saint-Charles',
                'province' => 'QC',
                'code_postal' => 'G3G 1C4',
                'telephone' => '418-890-1234',
                'email' => 'arts@lac-st-charles.ca',
                'proprietaire' => 'Michel Lessard',
                'active' => true,
            ],
            [
                'nom' => 'École Stoneham',
                'adresse' => '369 Avenue Tewkesbury',
                'ville' => 'Stoneham',
                'province' => 'QC',
                'code_postal' => 'G3C 1S1',
                'telephone' => '418-901-2345',
                'email' => 'ecole@stoneham-karate.ca',
                'proprietaire' => 'Robert Lapointe',
                'active' => true,
            ],
            [
                'nom' => 'Dojo Shannon',
                'adresse' => '741 Rue Shannon',
                'ville' => 'Shannon',
                'province' => 'QC',
                'code_postal' => 'G3S 1B7',
                'telephone' => '418-012-3456',
                'email' => 'dojo@shannon.ca',
                'proprietaire' => 'Louise Paradis',
                'active' => true,
            ],
            [
                'nom' => 'Centre Fossambault',
                'adresse' => '852 Boulevard Fossambault',
                'ville' => 'Fossambault-sur-le-Lac',
                'province' => 'QC',
                'code_postal' => 'G3N 1W6',
                'telephone' => '418-123-4567',
                'email' => 'centre@fossambault.ca',
                'proprietaire' => 'André Simard',
                'active' => true,
            ],
            [
                'nom' => 'École Cap-Rouge',
                'adresse' => '963 Rue Cap-Rouge',
                'ville' => 'Cap-Rouge',
                'province' => 'QC',
                'code_postal' => 'G1Y 1G5',
                'telephone' => '418-234-5678',
                'email' => 'ecole@cap-rouge.ca',
                'proprietaire' => 'Joanne Bélanger',
                'active' => true,
            ],
            [
                'nom' => 'Académie Pont-Rouge',
                'adresse' => '159 Avenue de Pont-Rouge',
                'ville' => 'Pont-Rouge',
                'province' => 'QC',
                'code_postal' => 'G3H 1L8',
                'telephone' => '418-345-6789',
                'email' => 'academie@pont-rouge.ca',
                'proprietaire' => 'Claude Thibault',
                'active' => true,
            ],
            [
                'nom' => 'Dojo Donnacona',
                'adresse' => '753 Rue Jacques-Cartier',
                'ville' => 'Donnacona',
                'province' => 'QC',
                'code_postal' => 'G3M 1B4',
                'telephone' => '418-456-7890',
                'email' => 'dojo@donnacona.ca',
                'proprietaire' => 'Brigitte Giguère',
                'active' => true,
            ],
            [
                'nom' => 'Club Neuville',
                'adresse' => '486 Route 138',
                'ville' => 'Neuville',
                'province' => 'QC',
                'code_postal' => 'G0A 2R0',
                'telephone' => '418-567-8901',
                'email' => 'club@neuville.ca',
                'proprietaire' => 'Normand Veilleux',
                'active' => true,
            ],
            [
                'nom' => 'École Portneuf',
                'adresse' => '357 Rue Principale',
                'ville' => 'Portneuf',
                'province' => 'QC',
                'code_postal' => 'G0A 2Y0',
                'telephone' => '418-678-9012',
                'email' => 'ecole@portneuf.ca',
                'proprietaire' => 'Gaétan Marcotte',
                'active' => true,
            ],
            [
                'nom' => 'Dojo Cap-Santé',
                'adresse' => '268 Rue du Fleuve',
                'ville' => 'Cap-Santé',
                'province' => 'QC',
                'code_postal' => 'G0A 1L0',
                'telephone' => '418-789-0123',
                'email' => 'dojo@cap-sante.ca',
                'proprietaire' => 'Chantal Huot',
                'active' => true,
            ],
            [
                'nom' => 'Centre Deschambault',
                'adresse' => '179 Chemin du Roy',
                'ville' => 'Deschambault-Grondines',
                'province' => 'QC',
                'code_postal' => 'G0A 1S0',
                'telephone' => '418-890-1234',
                'email' => 'centre@deschambault.ca',
                'proprietaire' => 'Réal Frenette',
                'active' => true,
            ],
            [
                'nom' => 'École Saint-Casimir',
                'adresse' => '591 Rue Tessier',
                'ville' => 'Saint-Casimir',
                'province' => 'QC',
                'code_postal' => 'G0A 3L0',
                'telephone' => '418-901-2345',
                'email' => 'ecole@st-casimir.ca',
                'proprietaire' => 'Denise Cantin',
                'active' => true,
            ],
            [
                'nom' => 'Académie Saint-Ubalde',
                'adresse' => '402 Rue de l\'Église',
                'ville' => 'Saint-Ubalde',
                'province' => 'QC',
                'code_postal' => 'G0A 4L0',
                'telephone' => '418-012-3456',
                'email' => 'academie@st-ubalde.ca',
                'proprietaire' => 'Alain Drolet',
                'active' => true,
            ],
            [
                'nom' => 'Dojo Lac-aux-Sables',
                'adresse' => '315 Avenue du Lac',
                'ville' => 'Lac-aux-Sables',
                'province' => 'QC',
                'code_postal' => 'G0X 1M0',
                'telephone' => '418-123-4567',
                'email' => 'dojo@lac-aux-sables.ca',
                'proprietaire' => 'Gilles Hamelin',
                'active' => true,
            ],
            [
                'nom' => 'Centre Saint-Tite',
                'adresse' => '628 Rue Principale',
                'ville' => 'Saint-Tite',
                'province' => 'QC',
                'code_postal' => 'G0X 3H0',
                'telephone' => '418-234-5678',
                'email' => 'centre@saint-tite.ca',
                'proprietaire' => 'Céline Rousseau',
                'active' => true,
            ],
        ];

        foreach ($ecoles as $ecole) {
            Ecole::updateOrCreate(
                ['nom' => $ecole['nom']],
                $ecole
            );
        }
    }
}
