<?php

namespace Database\Seeders;

use App\Models\Ecole;
use Illuminate\Database\Seeder;

class EcoleSeeder extends Seeder
{
    public function run(): void
    {
        $ecoles = [
            [
                'nom' => 'Studios Unis Montréal Centre',
                'code' => 'MTL',
                'adresse' => '123 Rue Principale',
                'ville' => 'Montréal',
                'province' => 'QC',
                'code_postal' => 'H1A 1A1',
                'telephone' => '514-555-0100',
                'email' => 'montreal@studiosunisqc.com',
                'site_web' => 'https://montreal.studiosunisqc.com',
                'description' => 'École principale de Montréal, centre-ville',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Québec',
                'code' => 'QBC',
                'adresse' => '456 Boulevard René-Lévesque',
                'ville' => 'Québec',
                'province' => 'QC',
                'code_postal' => 'G1K 2K2',
                'telephone' => '418-555-0200',
                'email' => 'quebec@studiosunisqc.com',
                'site_web' => 'https://quebec.studiosunisqc.com',
                'description' => 'École de la capitale nationale',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Trois-Rivières',
                'code' => 'TR',
                'adresse' => '789 Rue des Forges',
                'ville' => 'Trois-Rivières',
                'province' => 'QC',
                'code_postal' => 'G9A 3A3',
                'telephone' => '819-555-0300',
                'email' => 'troisrivieres@studiosunisqc.com',
                'site_web' => 'https://troisrivieres.studiosunisqc.com',
                'description' => 'École de la Mauricie',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Sherbrooke',
                'code' => 'SHB',
                'adresse' => '321 Rue King Ouest',
                'ville' => 'Sherbrooke',
                'province' => 'QC',
                'code_postal' => 'J1H 4B4',
                'telephone' => '819-555-0400',
                'email' => 'sherbrooke@studiosunisqc.com',
                'site_web' => 'https://sherbrooke.studiosunisqc.com',
                'description' => 'École de l\'Estrie',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Gatineau',
                'code' => 'GAT',
                'adresse' => '654 Boulevard Maloney',
                'ville' => 'Gatineau',
                'province' => 'QC',
                'code_postal' => 'J8T 5C5',
                'telephone' => '819-555-0500',
                'email' => 'gatineau@studiosunisqc.com',
                'site_web' => 'https://gatineau.studiosunisqc.com',
                'description' => 'École de l\'Outaouais',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis St-Émile',
                'code' => 'STE',
                'adresse' => '987 Chemin Royal',
                'ville' => 'Saint-Émile',
                'province' => 'QC',
                'code_postal' => 'G3E 6D6',
                'telephone' => '418-555-0600',
                'email' => 'stemile@studiosunisqc.com',
                'site_web' => 'https://stemile.studiosunisqc.com',
                'description' => 'École de Saint-Émile, région de Québec',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Laval',
                'code' => 'LAV',
                'adresse' => '147 Boulevard Saint-Martin',
                'ville' => 'Laval',
                'province' => 'QC',
                'code_postal' => 'H7M 7E7',
                'telephone' => '450-555-0700',
                'email' => 'laval@studiosunisqc.com',
                'site_web' => 'https://laval.studiosunisqc.com',
                'description' => 'École de Laval',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Longueuil',
                'code' => 'LNG',
                'adresse' => '258 Chemin de Chambly',
                'ville' => 'Longueuil',
                'province' => 'QC',
                'code_postal' => 'J4J 8F8',
                'telephone' => '450-555-0800',
                'email' => 'longueuil@studiosunisqc.com',
                'site_web' => 'https://longueuil.studiosunisqc.com',
                'description' => 'École de la Rive-Sud',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Saguenay',
                'code' => 'SAG',
                'adresse' => '369 Rue Racine',
                'ville' => 'Saguenay',
                'province' => 'QC',
                'code_postal' => 'G7H 9G9',
                'telephone' => '418-555-0900',
                'email' => 'saguenay@studiosunisqc.com',
                'site_web' => 'https://saguenay.studiosunisqc.com',
                'description' => 'École du Saguenay-Lac-Saint-Jean',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Rimouski',
                'code' => 'RIM',
                'adresse' => '741 Rue Saint-Germain',
                'ville' => 'Rimouski',
                'province' => 'QC',
                'code_postal' => 'G5L 0H0',
                'telephone' => '418-555-1000',
                'email' => 'rimouski@studiosunisqc.com',
                'site_web' => 'https://rimouski.studiosunisqc.com',
                'description' => 'École du Bas-Saint-Laurent',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Drummondville',
                'code' => 'DRV',
                'adresse' => '852 Rue Lindsay',
                'ville' => 'Drummondville',
                'province' => 'QC',
                'code_postal' => 'J2B 1I1',
                'telephone' => '819-555-1100',
                'email' => 'drummondville@studiosunisqc.com',
                'site_web' => 'https://drummondville.studiosunisqc.com',
                'description' => 'École du Centre-du-Québec',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Granby',
                'code' => 'GRB',
                'adresse' => '963 Rue Principale',
                'ville' => 'Granby',
                'province' => 'QC',
                'code_postal' => 'J2G 2J2',
                'telephone' => '450-555-1200',
                'email' => 'granby@studiosunisqc.com',
                'site_web' => 'https://granby.studiosunisqc.com',
                'description' => 'École de la Haute-Yamaska',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Victoriaville',
                'code' => 'VIC',
                'adresse' => '174 Boulevard Jutras',
                'ville' => 'Victoriaville',
                'province' => 'QC',
                'code_postal' => 'G6P 3K3',
                'telephone' => '819-555-1300',
                'email' => 'victoriaville@studiosunisqc.com',
                'site_web' => 'https://victoriaville.studiosunisqc.com',
                'description' => 'École de Victoriaville',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Saint-Hyacinthe',
                'code' => 'STH',
                'adresse' => '285 Avenue Saint-Simon',
                'ville' => 'Saint-Hyacinthe',
                'province' => 'QC',
                'code_postal' => 'J2S 4L4',
                'telephone' => '450-555-1400',
                'email' => 'sainthyacinthe@studiosunisqc.com',
                'site_web' => 'https://sainthyacinthe.studiosunisqc.com',
                'description' => 'École de Saint-Hyacinthe',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Brossard',
                'code' => 'BRS',
                'adresse' => '396 Boulevard Taschereau',
                'ville' => 'Brossard',
                'province' => 'QC',
                'code_postal' => 'J4W 5M5',
                'telephone' => '450-555-1500',
                'email' => 'brossard@studiosunisqc.com',
                'site_web' => 'https://brossard.studiosunisqc.com',
                'description' => 'École de Brossard',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Blainville',
                'code' => 'BLA',
                'adresse' => '507 Boulevard du Curé-Labelle',
                'ville' => 'Blainville',
                'province' => 'QC',
                'code_postal' => 'J7C 6N6',
                'telephone' => '450-555-1600',
                'email' => 'blainville@studiosunisqc.com',
                'site_web' => 'https://blainville.studiosunisqc.com',
                'description' => 'École de Blainville',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Repentigny',
                'code' => 'REP',
                'adresse' => '618 Rue Notre-Dame',
                'ville' => 'Repentigny',
                'province' => 'QC',
                'code_postal' => 'J6A 7O7',
                'telephone' => '450-555-1700',
                'email' => 'repentigny@studiosunisqc.com',
                'site_web' => 'https://repentigny.studiosunisqc.com',
                'description' => 'École de Repentigny',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Terrebonne',
                'code' => 'TER',
                'adresse' => '729 Montée Masson',
                'ville' => 'Terrebonne',
                'province' => 'QC',
                'code_postal' => 'J6W 8P8',
                'telephone' => '450-555-1800',
                'email' => 'terrebonne@studiosunisqc.com',
                'site_web' => 'https://terrebonne.studiosunisqc.com',
                'description' => 'École de Terrebonne',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Saint-Jean-sur-Richelieu',
                'code' => 'SJR',
                'adresse' => '830 Rue Richelieu',
                'ville' => 'Saint-Jean-sur-Richelieu',
                'province' => 'QC',
                'code_postal' => 'J3A 9Q9',
                'telephone' => '450-555-1900',
                'email' => 'saintjean@studiosunisqc.com',
                'site_web' => 'https://saintjean.studiosunisqc.com',
                'description' => 'École de Saint-Jean-sur-Richelieu',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Châteauguay',
                'code' => 'CHG',
                'adresse' => '941 Boulevard Saint-Jean-Baptiste',
                'ville' => 'Châteauguay',
                'province' => 'QC',
                'code_postal' => 'J6K 0R0',
                'telephone' => '450-555-2000',
                'email' => 'chateauguay@studiosunisqc.com',
                'site_web' => 'https://chateauguay.studiosunisqc.com',
                'description' => 'École de Châteauguay',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Mascouche',
                'code' => 'MAS',
                'adresse' => '152 Chemin Sainte-Marie',
                'ville' => 'Mascouche',
                'province' => 'QC',
                'code_postal' => 'J7L 1S1',
                'telephone' => '450-555-2100',
                'email' => 'mascouche@studiosunisqc.com',
                'site_web' => 'https://mascouche.studiosunisqc.com',
                'description' => 'École de Mascouche',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Mirabel',
                'code' => 'MIR',
                'adresse' => '263 Rue Saint-Vincent',
                'ville' => 'Mirabel',
                'province' => 'QC',
                'code_postal' => 'J7J 2T2',
                'telephone' => '450-555-2200',
                'email' => 'mirabel@studiosunisqc.com',
                'site_web' => 'https://mirabel.studiosunisqc.com',
                'description' => 'École de Mirabel',
                'active' => true,
            ],
        ];

        foreach ($ecoles as $ecoleData) {
            Ecole::firstOrCreate(
                ['code' => $ecoleData['code']],
                $ecoleData
            );
        }

        $this->command->info('✅ ' . count($ecoles) . ' écoles Studios Unis créées (codes courts)');
    }
}
