<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ecole;

class EcolesSeeder extends Seeder
{
    public function run(): void
    {
        $ecoles = [
            [
                'nom' => 'Studios Unis St-Émile',
                'code' => 'SE',
                'adresse' => '123 rue Principale',
                'ville' => 'Saint-Émile',
                'province' => 'QC',
                'code_postal' => 'G3E 1A1',
                'telephone' => '418-123-4567',
                'email' => 'stemile@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/st-emile',
                'description' => 'École de karaté située à Saint-Émile',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Québec Centre',
                'code' => 'QC',
                'adresse' => '456 avenue des Érables',
                'ville' => 'Québec',
                'province' => 'QC',
                'code_postal' => 'G1R 2B3',
                'telephone' => '418-234-5678',
                'email' => 'quebec@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/quebec',
                'description' => 'École principale située dans le centre de Québec',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Sainte-Foy',
                'code' => 'SF',
                'adresse' => '789 chemin Sainte-Foy',
                'ville' => 'Sainte-Foy',
                'province' => 'QC',
                'code_postal' => 'G1V 3C4',
                'telephone' => '418-345-6789',
                'email' => 'saintefoy@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/sainte-foy',
                'description' => 'École de karaté à Sainte-Foy',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Lévis',
                'code' => 'LV',
                'adresse' => '321 rue du Roi',
                'ville' => 'Lévis',
                'province' => 'QC',
                'code_postal' => 'G6V 4D5',
                'telephone' => '418-456-7890',
                'email' => 'levis@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/levis',
                'description' => 'École de karaté sur la Rive-Sud',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Charlesbourg',
                'code' => 'CB',
                'adresse' => '654 boulevard Henri-Bourassa',
                'ville' => 'Charlesbourg',
                'province' => 'QC',
                'code_postal' => 'G1H 5E6',
                'telephone' => '418-567-8901',
                'email' => 'charlesbourg@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/charlesbourg',
                'description' => 'École de karaté à Charlesbourg',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Beauport',
                'code' => 'BP',
                'adresse' => '987 avenue Royale',
                'ville' => 'Beauport',
                'province' => 'QC',
                'code_postal' => 'G1E 6F7',
                'telephone' => '418-678-9012',
                'email' => 'beauport@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/beauport',
                'description' => 'École de karaté à Beauport',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Ancienne-Lorette',
                'code' => 'AL',
                'adresse' => '147 rue Notre-Dame',
                'ville' => 'Ancienne-Lorette',
                'province' => 'QC',
                'code_postal' => 'G2E 7G8',
                'telephone' => '418-789-0123',
                'email' => 'lorette@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/ancienne-lorette',
                'description' => 'École de karaté à l\'Ancienne-Lorette',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Cap-Rouge',
                'code' => 'CR',
                'adresse' => '258 rue Saint-Félix',
                'ville' => 'Cap-Rouge',
                'province' => 'QC',
                'code_postal' => 'G1Y 8H9',
                'telephone' => '418-890-1234',
                'email' => 'caprouge@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/cap-rouge',
                'description' => 'École de karaté à Cap-Rouge',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Val-Bélair',
                'code' => 'VB',
                'adresse' => '369 boulevard de la Colline',
                'ville' => 'Val-Bélair',
                'province' => 'QC',
                'code_postal' => 'G3K 9I0',
                'telephone' => '418-901-2345',
                'email' => 'valbelair@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/val-belair',
                'description' => 'École de karaté à Val-Bélair',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Montmagny',
                'code' => 'MM',
                'adresse' => '147 boulevard Taché Est',
                'ville' => 'Montmagny',
                'province' => 'QC',
                'code_postal' => 'G5V 1C5',
                'telephone' => '418-248-3456',
                'email' => 'montmagny@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/montmagny',
                'description' => 'École de karaté à Montmagny',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Thetford Mines',
                'code' => 'TM',
                'adresse' => '789 rue Notre-Dame Ouest',
                'ville' => 'Thetford Mines',
                'province' => 'QC',
                'code_postal' => 'G6G 1J2',
                'telephone' => '418-335-4567',
                'email' => 'thetford@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/thetford',
                'description' => 'École de karaté à Thetford Mines',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Rivière-du-Loup',
                'code' => 'RDL',
                'adresse' => '456 rue Lafontaine',
                'ville' => 'Rivière-du-Loup',
                'province' => 'QC',
                'code_postal' => 'G5R 3A7',
                'telephone' => '418-867-5309',
                'email' => 'riviere@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/riviere-du-loup',
                'description' => 'École de karaté à Rivière-du-Loup',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Trois-Rivières',
                'code' => 'TR',
                'adresse' => '123 rue des Forges',
                'ville' => 'Trois-Rivières',
                'province' => 'QC',
                'code_postal' => 'G9A 2G7',
                'telephone' => '819-374-5678',
                'email' => 'troisrivieres@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/trois-rivieres',
                'description' => 'École de karaté à Trois-Rivières',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Sherbrooke',
                'code' => 'SH',
                'adresse' => '789 rue King Ouest',
                'ville' => 'Sherbrooke',
                'province' => 'QC',
                'code_postal' => 'J1H 1R3',
                'telephone' => '819-563-7890',
                'email' => 'sherbrooke@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/sherbrooke',
                'description' => 'École de karaté à Sherbrooke',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Drummondville',
                'code' => 'DV',
                'adresse' => '456 rue Hériot',
                'ville' => 'Drummondville',
                'province' => 'QC',
                'code_postal' => 'J2C 1J8',
                'telephone' => '819-477-1234',
                'email' => 'drummondville@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/drummondville',
                'description' => 'École de karaté à Drummondville',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Granby',
                'code' => 'GR',
                'adresse' => '123 rue Principale',
                'ville' => 'Granby',
                'province' => 'QC',
                'code_postal' => 'J2G 2V4',
                'telephone' => '450-372-5678',
                'email' => 'granby@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/granby',
                'description' => 'École de karaté à Granby',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Saint-Hyacinthe',
                'code' => 'SHY',
                'adresse' => '789 avenue Sainte-Anne',
                'ville' => 'Saint-Hyacinthe',
                'province' => 'QC',
                'code_postal' => 'J2S 5G3',
                'telephone' => '450-773-9012',
                'email' => 'sainthyacinthe@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/saint-hyacinthe',
                'description' => 'École de karaté à Saint-Hyacinthe',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Victoriaville',
                'code' => 'VV',
                'adresse' => '456 boulevard Jutras Est',
                'ville' => 'Victoriaville',
                'province' => 'QC',
                'code_postal' => 'G6P 7H4',
                'telephone' => '819-357-3456',
                'email' => 'victoriaville@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/victoriaville',
                'description' => 'École de karaté à Victoriaville',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Chicoutimi',
                'code' => 'CH',
                'adresse' => '123 rue Racine Est',
                'ville' => 'Chicoutimi',
                'province' => 'QC',
                'code_postal' => 'G7H 1R9',
                'telephone' => '418-543-7890',
                'email' => 'chicoutimi@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/chicoutimi',
                'description' => 'École de karaté à Chicoutimi',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Rimouski',
                'code' => 'RM',
                'adresse' => '789 rue Saint-Germain Ouest',
                'ville' => 'Rimouski',
                'province' => 'QC',
                'code_postal' => 'G5L 4B3',
                'telephone' => '418-723-1234',
                'email' => 'rimouski@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/rimouski',
                'description' => 'École de karaté à Rimouski',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Rouyn-Noranda',
                'code' => 'RN',
                'adresse' => '456 avenue Larivière',
                'ville' => 'Rouyn-Noranda',
                'province' => 'QC',
                'code_postal' => 'J9X 4H5',
                'telephone' => '819-762-5678',
                'email' => 'rouyn@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/rouyn-noranda',
                'description' => 'École de karaté à Rouyn-Noranda',
                'active' => true,
            ],
            [
                'nom' => 'Studios Unis Sept-Îles',
                'code' => 'SI',
                'adresse' => '123 avenue Brochu',
                'ville' => 'Sept-Îles',
                'province' => 'QC',
                'code_postal' => 'G4R 2W7',
                'telephone' => '418-962-9012',
                'email' => 'septiles@studiosunisqc.com',
                'site_web' => 'https://studiosunisqc.com/sept-iles',
                'description' => 'École de karaté à Sept-Îles',
                'active' => true,
            ],
        ];

        foreach ($ecoles as $ecoleData) {
            Ecole::firstOrCreate(
                ['code' => $ecoleData['code']],
                $ecoleData
            );
        }
    }
}
