#!/bin/bash
echo "================================================"
echo "🏆 STUDIOSDB - AIDE SCRIPTS DISPONIBLES"
echo "================================================"
cd /home/studiosdb/studiosunisdb

echo ""
echo "🎯 SAUVEGARDE COMPLÈTE (RECOMMANDÉ):"
echo ""
echo "   ./BACKUP.sh"
echo "   └─ Sauvegarde intégrale projet StudiosDB"
echo "      • Code complet (app, database, resources, etc.)"
echo "      • Base de données (structure + données)"
echo "      • Documentation complète"
echo "      • Scripts utilitaires"
echo "      • Commit git avec changelog détaillé"
echo "      • État système complet"
echo ""

echo "🔍 VÉRIFICATIONS & ÉTAT:"
echo ""
echo "   ./STATUS.sh"
echo "   └─ État rapide projet (modules, DB, fichiers)"
echo ""
echo "   ./CHECK_BEFORE_BACKUP.sh"
echo "   └─ Vérifications prérequis sauvegarde"
echo ""

echo "🔧 MODULE COURS (SPÉCIFIQUE):"
echo ""
echo "   ./FIX_COMPLET_COURS.sh"
echo "   └─ Corrections contraintes DB module Cours"
echo ""
echo "   ./TEST_SIMULATION.sh"
echo "   └─ Tests validation module Cours"
echo ""
echo "   ./BACKUP_COURS.sh"
echo "   └─ Sauvegarde module Cours uniquement"
echo ""

echo "💾 SAUVEGARDES PARTIELLES:"
echo ""
echo "   ./BACKUP_PROJECT_COMPLETE.sh"
echo "   └─ Code complet (sans DB)"
echo ""
echo "   ./BACKUP_DATABASE.sh"  
echo "   └─ Base de données uniquement"
echo ""

echo "🌐 INTERFACE UTILISATEUR:"
echo ""
echo "   php artisan serve --port=8001"
echo "   └─ Démarrer serveur développement"
echo "      → http://127.0.0.1:8001"
echo ""

echo "📝 DOCUMENTATION:"
echo ""
echo "   cat README_STATUS.md"
echo "   └─ État détaillé projet"
echo ""
echo "   cat docs/ADR-*.md"
echo "   └─ Documentation technique (ADR)"
echo ""

echo "🐙 GITHUB & SYNCHRONISATION:"
echo ""
echo "   ./GITHUB.sh"
echo "   └─ Menu complet GitHub (analyse + sync + config)"
echo ""
echo "   ./CHECK_GIT.sh"
echo "   └─ Vérification rapide état git"
echo ""
echo "   ./SYNC_GITHUB.sh"
echo "   └─ Synchronisation avec GitHub"
echo ""
echo "   ./SETUP_GITHUB.sh"
echo "   └─ Configuration initiale GitHub"
echo ""
echo "   ./ANALYZE_GITHUB.sh"
echo "   └─ Analyse détaillée git/GitHub"
echo ""

echo "================================================"
echo "📊 ÉTAT ACTUEL STUDIOSDB:"
echo "================================================"

echo ""
echo "📋 MODULES:"
echo "   ✅ J1 Bootstrap sécurité   : DONE"
echo "   ✅ J2 Dashboard (UI ref)   : DONE"
echo "   ✅ J3 Cours (fonct ref)    : DONE (Corrections DB OK)"
echo "   🟡 J4 Utilisateurs         : TODO (prochaine étape)"
echo "   🟡 J5 Membres             : TODO"
echo "   🟡 J6 Inscription self     : TODO"
echo ""

echo "🏗️ TECH STACK:"
echo "   Laravel 12.x + Inertia + Vue 3 + Tailwind + MySQL"
echo ""

echo "🎯 RECOMMANDATION IMMÉDIATE:"
echo ""
echo "   ./BACKUP.sh"
echo ""
echo "   ↳ Sauvegarde complète avant passage au Module J4"
echo ""

echo "================================================"
echo "📞 STUDIOSDB - Aide & Support Intégré"  
echo "================================================"

# Vérifier si on est dans le bon répertoire
if [ ! -f "artisan" ]; then
    echo ""
    echo "⚠️  ATTENTION: Vous n'êtes pas dans le répertoire StudiosDB"
    echo "   cd /home/studiosdb/studiosunisdb"
    echo ""
fi

# Vérifier statut backup
if [ -f ".backup_status" ]; then
    echo ""
    echo "📊 DERNIÈRE SAUVEGARDE:"
    cat .backup_status
    echo ""
fi
